name: WltpNotiveFetcher
version: 1.0
author: WLTP
main: world.wltp.notice.NoticePlugin
website: https://www.wltp.world/
api-version: 1.21
commands:
  중요공지:
    description: 중요공지를 가져옵니다
  일반공지:
    description: 일반공지를 가져옵니다
  아카이브공지:
    description: 아카이브공지를 가져옵니다

permissions:
  notice.use:
    description: 공지를 확인할 수 있는 권한
    default: true
